name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create release PR or version
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: 'chore(release): version packages'
          title: 'chore: release new version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to npm (Optional)
      #   if: github.ref == 'refs/heads/main'
      #   run: pnpm publish --no-git-checks
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create ZIP Archive
        run: |
          zip -r release.zip . -x "*.git*" "node_modules/*" "*.DS_Store"

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            🚀 **New Release v${{ github.run_number }}**
            - Auto-generated from main branch.
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
