name: Validate Changeset

on:
  pull_request:
    branches:
      - main

jobs:
  check-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Check for PR labels
        id: check_labels
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });
            const labels = response.data.map(label => label.name);
            if (labels.includes('no-changeset')) {
              console.log("Skipping changeset check due to 'no-changeset' label.");
              process.exit(0);
            }
              
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we can compare changes

      - name: Check for new changeset
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^.changeset/.*\.md$'; then
            echo "✅ A new changeset has been added."
          else
            echo "❌ No new changeset found in this PR. Please run 'pnpm changeset' and commit the file."
            exit 1
          fi
